### PR TITLE
Cherry-pick nikic's APint fixes

### PR DESCRIPTION
**Pull request by akiramenai**

### CODE REVIEW

**Comment by PavelKopyl** [comment]
I wonder, why do we need to revert the assertions in APInt constructor -  "Revert "Assert correct values in APInt constructor""? Are that assertions triggered on our codebase?

**Review by vladimirradosavljevic — APPROVED** [review]
LGTM.
Do we need https://github.com/matter-labs/era-compiler-llvm/pull/693/commits/63c7385fb88cf32245e87bd82ce9cf65d44f9bc0, https://github.com/matter-labs/era-compiler-llvm/pull/693/commits/d5b2d0d1286637b72bf335a942ae397c5a510ac0, https://github.com/matter-labs/era-compiler-llvm/pull/693/commits/ff6bca2d5f39ccf3c332a99fe7bd512b9d4ba447 and https://github.com/matter-labs/era-compiler-llvm/pull/693/commits/581a8f1726d1a289bb5710b03ce1aaef1aa0fcaa? It seems that problem that fixes https://github.com/matter-labs/era-compiler-llvm/pull/693/commits/581a8f1726d1a289bb5710b03ce1aaef1aa0fcaa doesn't exist in LLVM 17, and we cherry picked new functionality with the fix? Am I missing something?

**Comment by akiramenai** [comment]
@PavelKopyl we've already merged pieces of nikic's patches when they were under development, so basically I reverted the old version, then cherry-picked accepted patches, then reapplied the current nikic's WIP.

**Comment by akiramenai** [comment]
@vladimirradosavljevic I didn't dig deep into the transformation itself, but you listed https://github.com/llvm/llvm-project/commit/3512bcc2e9ab06b0ae2cab78744550b515e54184 in the ticket. The rest are to apply this patch cleanly, aside from introducing new functionality it reimplements the old one and then we apply the patch. So I don't that confident that there wasn't a bug in LLVM 17 and prefer to cherry-pick.

**Pull request merged**
