### PR TITLE
[SyncVM] Always inline functions with one call site

### PR DESCRIPTION
**Pull request by vladimirradosavljevic**

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.187 ║
║ Best                               40.000 ║
║ Worst                             -62.577 ║
║ Total                               0.209 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.183 ║
║ Best                               77.178 ║
║ Worst                             -34.783 ║
║ Total                               0.048 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.086 ║
║ Best                               69.189 ║
║ Worst                             -34.926 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.347 ║
║ Best                                9.756 ║
║ Worst                              -1.876 ║
║ Total                               0.464 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.083 ║
║ Best                                3.175 ║
║ Worst                              -0.789 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.150 ║
║ Best                               19.075 ║
║ Worst                              -0.041 ║
║ Total                               0.009 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.148 ║
║ Best                               40.000 ║
║ Worst                             -38.356 ║
║ Total                               0.187 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.145 ║
║ Best                               77.178 ║
║ Worst                             -10.000 ║
║ Total                               0.048 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.090 ║
║ Best                               69.189 ║
║ Worst                              -7.229 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.347 ║
║ Best                                9.756 ║
║ Worst                              -1.876 ║
║ Total                               0.464 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.083 ║
║ Best                                3.175 ║
║ Worst                              -0.789 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.150 ║
║ Best                               19.075 ║
║ Worst                              -0.041 ║
║ Total                               0.009 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.148 ║
║ Best                               40.000 ║
║ Worst                             -38.356 ║
║ Total                               0.187 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.145 ║
║ Best                               77.178 ║
║ Worst                             -10.000 ║
║ Total                               0.048 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.090 ║
║ Best                               69.189 ║
║ Worst                              -7.229 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.347 ║
║ Best                                9.756 ║
║ Worst                              -1.876 ║
║ Total                               0.464 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.083 ║
║ Best                                3.175 ║
║ Worst                              -0.789 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.150 ║
║ Best                               19.075 ║
║ Worst                              -0.041 ║
║ Total                               0.009 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.149 ║
║ Best                               40.000 ║
║ Worst                             -38.356 ║
║ Total                               0.188 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.145 ║
║ Best                               77.178 ║
║ Worst                             -10.000 ║
║ Total                               0.048 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.090 ║
║ Best                               69.189 ║
║ Worst                              -7.229 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.347 ║
║ Best                                9.756 ║
║ Worst                              -1.876 ║
║ Total                               0.464 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.083 ║
║ Best                                3.175 ║
║ Worst                              -0.789 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.150 ║
║ Best                               19.075 ║
║ Worst                              -0.041 ║
║ Total                               0.009 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.149 ║
║ Best                               40.000 ║
║ Worst                             -38.356 ║
║ Total                               0.188 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.145 ║
║ Best                               77.178 ║
║ Worst                             -10.000 ║
║ Total                               0.048 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.090 ║
║ Best                               69.189 ║
║ Worst                              -7.229 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.347 ║
║ Best                                9.756 ║
║ Worst                              -1.876 ║
║ Total                               0.464 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.083 ║
║ Best                                3.175 ║
║ Worst                              -0.789 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.150 ║
║ Best                               19.075 ║
║ Worst                              -0.041 ║
║ Total                               0.009 ║
╚═══════════════════════════════════════════╝

```

**Review by akiramenai — APPROVED** [review]
LGTM, thanks.
Always inline bypasses the dynamic alloca issue, right?

**Comment by vladimirradosavljevic** [comment]
> LGTM, thanks. Always inline bypasses the dynamic alloca issue, right?

Yes, exactly. Dynamic alloca issue happens during cost calculation, but if there is always inline attribute, cost is not calculated and the function is inlined.

**Comment by akiramenai** [comment]
Thank you. A clever solution and no local changes.

**Pull request merged**
