### PR TITLE
[DO NOT MERGE] Tweak inlining

### PR DESCRIPTION
**Pull request by vladimirradosavljevic**

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.158 ║
║ Best                               36.364 ║
║ Worst                             -50.386 ║
║ Total                               0.149 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.051 ║
║ Best                               73.859 ║
║ Worst                             -424.828 ║
║ Total                              -0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.109 ║
║ Best                               65.162 ║
║ Worst                             -388.235 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.228 ║
║ Best                                9.056 ║
║ Worst                             -23.548 ║
║ Total                              -0.640 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.038 ║
║ Best                                2.069 ║
║ Worst                              -0.592 ║
║ Total                               0.013 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.123 ║
║ Best                               18.382 ║
║ Worst                              -1.625 ║
║ Total                              -0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by akiramenai** [comment]
You might be interested in https://github.com/matter-labs/compiler-llvm/pull/133
I've already tried to hoist alloca early as dynamic alloca prevents inlining. But the results weren't that great and compilation time increased.

**Comment by vladimirradosavljevic** [comment]
> You might be interested in #133 I've already tried to hoist alloca early as dynamic alloca prevents inlining. But the results weren't that great and compilation time increased.

Ah, I didn't know we tried this before. What I have seen from one of the tests is that with this change + threshold multiplier we are now inlining huge functions. Maybe with these two patches combined we can get nice numbers.

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                 -inf ║
║ Best                               78.655 ║
║ Worst                             -61.538 ║
║ Total                               0.260 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                               73.859 ║
║ Worst                             -424.828 ║
║ Total                              -0.439 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                               65.162 ║
║ Worst                             -14849.162 ║
║ Total                              -0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                2.731 ║
║ Best                               65.027 ║
║ Worst                             -23.529 ║
║ Total                               9.034 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -1.506 ║
║ Best                                5.714 ║
║ Worst                             -47.366 ║
║ Total                              -3.243 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.382 ║
║ Best                               14.855 ║
║ Worst                             -44.789 ║
║ Total                              -0.076 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.401 ║
║ Best                               55.426 ║
║ Worst                             -50.386 ║
║ Total                              -0.124 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.312 ║
║ Best                               73.859 ║
║ Worst                             -424.828 ║
║ Total                              -0.017 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.182 ║
║ Best                               65.162 ║
║ Worst                             -14844.392 ║
║ Total                              -0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.868 ║
║ Best                               11.984 ║
║ Worst                             -23.529 ║
║ Total                               0.146 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.269 ║
║ Best                                2.108 ║
║ Worst                             -10.870 ║
║ Total                              -0.029 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.250 ║
║ Best                               18.382 ║
║ Worst                             -46.120 ║
║ Total                              -0.005 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.150 ║
║ Best                               55.426 ║
║ Worst                             -50.386 ║
║ Total                               0.208 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.031 ║
║ Best                               73.859 ║
║ Worst                             -424.828 ║
║ Total                              -0.005 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.064 ║
║ Best                               65.162 ║
║ Worst                             -14844.392 ║
║ Total                              -0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.075 ║
║ Best                                9.056 ║
║ Worst                             -23.548 ║
║ Total                               0.075 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.004 ║
║ Best                                2.108 ║
║ Worst                              -4.367 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.128 ║
║ Best                               18.382 ║
║ Worst                              -0.347 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.170 ║
║ Best                               36.019 ║
║ Worst                             -31.155 ║
║ Total                               0.137 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.057 ║
║ Best                               34.864 ║
║ Worst                             -15.686 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.112 ║
║ Best                               35.540 ║
║ Worst                              -3.607 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.267 ║
║ Best                                9.056 ║
║ Worst                             -25.432 ║
║ Total                              -0.753 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.032 ║
║ Best                                1.667 ║
║ Worst                              -0.161 ║
║ Total                               0.008 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.122 ║
║ Best                               18.382 ║
║ Worst                              -1.839 ║
║ Total                              -0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.168 ║
║ Best                               55.426 ║
║ Worst                             -31.155 ║
║ Total                               0.209 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.041 ║
║ Best                               34.864 ║
║ Worst                             -39.904 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.075 ║
║ Best                               35.540 ║
║ Worst                             -14844.392 ║
║ Total                              -0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.113 ║
║ Best                                9.056 ║
║ Worst                             -25.432 ║
║ Total                              -0.035 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.010 ║
║ Best                                1.667 ║
║ Worst                              -4.367 ║
║ Total                              -0.006 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.127 ║
║ Best                               18.382 ║
║ Worst                              -0.528 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.170 ║
║ Best                               36.019 ║
║ Worst                             -31.155 ║
║ Total                               0.137 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.057 ║
║ Best                               34.864 ║
║ Worst                             -15.686 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.112 ║
║ Best                               35.540 ║
║ Worst                              -3.607 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.267 ║
║ Best                                9.056 ║
║ Worst                             -25.432 ║
║ Total                              -0.753 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.032 ║
║ Best                                1.667 ║
║ Worst                              -0.161 ║
║ Total                               0.008 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.122 ║
║ Best                               18.382 ║
║ Worst                              -1.839 ║
║ Total                              -0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.185 ║
║ Best                               36.019 ║
║ Worst                             -62.774 ║
║ Total                               0.164 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.066 ║
║ Best                               34.235 ║
║ Worst                             -10.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.113 ║
║ Best                               35.030 ║
║ Worst                              -3.607 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.235 ║
║ Best                                9.106 ║
║ Worst                             -24.027 ║
║ Total                              -0.692 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.036 ║
║ Best                                3.175 ║
║ Worst                              -0.150 ║
║ Total                               0.010 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.123 ║
║ Best                               19.075 ║
║ Worst                              -1.693 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.185 ║
║ Best                               36.019 ║
║ Worst                             -62.774 ║
║ Total                               0.170 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.064 ║
║ Best                               34.235 ║
║ Worst                             -39.918 ║
║ Total                               0.003 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.109 ║
║ Best                               35.030 ║
║ Worst                             -215.850 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.232 ║
║ Best                                9.106 ║
║ Worst                             -24.027 ║
║ Total                              -0.688 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.037 ║
║ Best                                3.175 ║
║ Worst                              -0.150 ║
║ Total                               0.011 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.123 ║
║ Best                               19.075 ║
║ Worst                              -1.693 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.216 ║
║ Best                               45.614 ║
║ Worst                             -62.774 ║
║ Total                               0.143 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.098 ║
║ Best                               68.687 ║
║ Worst                             -10.000 ║
║ Total                               0.008 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.194 ║
║ Best                               48.685 ║
║ Worst                              -5.329 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.511 ║
║ Best                                9.106 ║
║ Worst                             -24.027 ║
║ Total                              -1.870 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.037 ║
║ Best                                3.175 ║
║ Worst                              -0.150 ║
║ Total                               0.011 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.111 ║
║ Best                               19.075 ║
║ Worst                              -4.119 ║
║ Total                              -0.004 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.185 ║
║ Best                               36.019 ║
║ Worst                             -62.774 ║
║ Total                               0.164 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.066 ║
║ Best                               34.235 ║
║ Worst                             -10.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.113 ║
║ Best                               35.030 ║
║ Worst                              -3.607 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.235 ║
║ Best                                9.106 ║
║ Worst                             -24.027 ║
║ Total                              -0.692 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.036 ║
║ Best                                3.175 ║
║ Worst                              -0.150 ║
║ Total                               0.010 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.123 ║
║ Best                               19.075 ║
║ Worst                              -1.693 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.148 ║
║ Best                               40.000 ║
║ Worst                             -38.356 ║
║ Total                               0.187 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.145 ║
║ Best                               77.178 ║
║ Worst                             -10.000 ║
║ Total                               0.048 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.090 ║
║ Best                               69.189 ║
║ Worst                              -7.229 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.347 ║
║ Best                                9.756 ║
║ Worst                              -1.876 ║
║ Total                               0.464 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.083 ║
║ Best                                3.175 ║
║ Worst                              -0.789 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.150 ║
║ Best                               19.075 ║
║ Worst                              -0.041 ║
║ Total                               0.009 ║
╚═══════════════════════════════════════════╝

```

**Comment by vladimirradosavljevic** [comment]
Moved to #310.

**Pull request closed without merging**
