### PR TITLE
[DO NOT MERGE] Add IntrNoMem attribute to int_eravm_getu128 intrinsic

### PR DESCRIPTION
**Pull request by vladimirradosavljevic**

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                              100.000 ║
║ Best                               75.214 ║
║ Worst                             -61.682 ║
║ Total                              10.866 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                              100.000 ║
║ Best                               87.464 ║
║ Worst                             -13.074 ║
║ Total                               2.632 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                              100.000 ║
║ Best                               85.003 ║
║ Worst                              -9.906 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                              100.000 ║
║ Best                               75.630 ║
║ Worst                             -14.085 ║
║ Total                               7.699 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                              100.000 ║
║ Best                               77.049 ║
║ Worst                             -31.429 ║
║ Total                               2.320 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                              100.000 ║
║ Best                               78.329 ║
║ Worst                             -20.675 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                3.713 ║
║ Best                               16.145 ║
║ Worst                              -0.382 ║
║ Total                               3.659 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                7.505 ║
║ Best                               38.776 ║
║ Worst                               0.000 ║
║ Total                               2.600 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                1.343 ║
║ Best                               24.612 ║
║ Worst                               0.000 ║
║ Total                               0.100 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                2.990 ║
║ Best                               16.627 ║
║ Worst                              -2.469 ║
║ Total                               3.800 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                6.240 ║
║ Best                               26.154 ║
║ Worst                              -3.571 ║
║ Total                               2.128 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.665 ║
║ Best                               16.007 ║
║ Worst                              -1.422 ║
║ Total                               0.094 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                              100.000 ║
║ Best                               75.214 ║
║ Worst                             -59.813 ║
║ Total                              12.377 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                              100.000 ║
║ Best                               87.464 ║
║ Worst                             -13.074 ║
║ Total                               2.638 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                              100.000 ║
║ Best                               85.003 ║
║ Worst                              -9.906 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                              100.000 ║
║ Best                               75.630 ║
║ Worst                             -21.277 ║
║ Total                               7.343 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                              100.000 ║
║ Best                               69.565 ║
║ Worst                             -22.674 ║
║ Total                               2.308 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                              100.000 ║
║ Best                               69.818 ║
║ Worst                             -20.675 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                3.992 ║
║ Best                               16.145 ║
║ Worst                              -0.382 ║
║ Total                               4.055 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                7.627 ║
║ Best                               38.776 ║
║ Worst                               0.000 ║
║ Total                               2.625 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                1.372 ║
║ Best                               24.612 ║
║ Worst                               0.000 ║
║ Total                               0.102 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                2.820 ║
║ Best                               16.169 ║
║ Worst                              -2.469 ║
║ Total                               3.432 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                6.128 ║
║ Best                               26.154 ║
║ Worst                              -3.571 ║
║ Total                               2.124 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.606 ║
║ Best                               16.007 ║
║ Worst                              -1.422 ║
║ Total                               0.094 ║
╚═══════════════════════════════════════════╝

```

**Comment by akiramenai** [comment]
I think we can add get, set, get test some tests to show that GVN works and merge it.

**Comment by vladimirradosavljevic** [comment]
> I think we can add get, set, get test some tests to show that GVN works and merge it.

Since I want to do one more experiment in this PR, I will create a new PR for intrinsic attributes with the proper tests.

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                              100.000 ║
║ Best                               75.214 ║
║ Worst                             -63.551 ║
║ Total                              12.696 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                              100.000 ║
║ Best                               87.464 ║
║ Worst                             -13.074 ║
║ Total                               2.748 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                              100.000 ║
║ Best                               93.737 ║
║ Worst                              -9.906 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                              100.000 ║
║ Best                               75.630 ║
║ Worst                             -21.277 ║
║ Total                               7.454 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                              100.000 ║
║ Best                               69.565 ║
║ Worst                             -22.674 ║
║ Total                               2.397 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                              100.000 ║
║ Best                               79.891 ║
║ Worst                             -20.675 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                3.996 ║
║ Best                               22.346 ║
║ Worst                              -3.683 ║
║ Total                               3.882 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                7.259 ║
║ Best                               38.776 ║
║ Worst                               0.000 ║
║ Total                               2.752 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                1.262 ║
║ Best                               24.612 ║
║ Worst                               0.000 ║
║ Total                               0.096 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                2.996 ║
║ Best                               22.297 ║
║ Worst                              -2.469 ║
║ Total                               3.474 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                5.964 ║
║ Best                               26.154 ║
║ Worst                              -3.571 ║
║ Total                               2.247 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.587 ║
║ Best                               16.007 ║
║ Worst                              -1.422 ║
║ Total                               0.089 ║
╚═══════════════════════════════════════════╝

```

**Pull request closed without merging**
