### PR TITLE
[WIP][EraVM] Do a further fold in select expand pass

### PR DESCRIPTION
**Pull request by TerryGuo**

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.001 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                2.857 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                1.562 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.001 ║
║ Best                                0.816 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                4.706 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                1.678 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                                1.100 ║
║ Best                                1.677 ║
║ Worst                               0.000 ║
║ Total                               1.312 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                0.245 ║
║ Best                                1.461 ║
║ Worst                               0.000 ║
║ Total                               0.783 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                0.239 ║
║ Best                                1.461 ║
║ Worst                               0.000 ║
║ Total                               0.073 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                0.444 ║
║ Best                                0.678 ║
║ Worst                               0.000 ║
║ Total                               0.492 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.231 ║
║ Best                                1.692 ║
║ Worst                               0.000 ║
║ Total                               1.298 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.229 ║
║ Best                                1.678 ║
║ Worst                               0.000 ║
║ Total                               0.124 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.081 ║
║ Worst                               0.000 ║
║ Total                               0.008 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.109 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.007 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.000 ║
║ Best                                0.040 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.032 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.002 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.006 ║
║ Best                                9.644 ║
║ Worst                               0.000 ║
║ Total                               0.026 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                               11.101 ║
║ Worst                               0.000 ║
║ Total                               0.010 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                               11.098 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.006 ║
║ Best                                8.814 ║
║ Worst                               0.000 ║
║ Total                               0.015 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               11.582 ║
║ Worst                               0.000 ║
║ Total                               0.010 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               11.482 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                                8.795 ║
║ Best                                9.644 ║
║ Worst                               0.000 ║
║ Total                               9.105 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                3.421 ║
║ Best                               11.101 ║
║ Worst                               0.000 ║
║ Total                               8.697 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                3.303 ║
║ Best                               11.098 ║
║ Worst                               0.000 ║
║ Total                               0.808 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                7.106 ║
║ Best                                8.814 ║
║ Worst                               0.000 ║
║ Total                               7.434 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                3.535 ║
║ Best                               11.582 ║
║ Worst                               0.000 ║
║ Total                               9.197 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                3.368 ║
║ Best                               11.482 ║
║ Worst                               0.000 ║
║ Total                               0.880 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.282 ║
║ Worst                               0.000 ║
║ Total                               0.008 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.310 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.014 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.222 ║
║ Worst                               0.000 ║
║ Total                               0.010 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.274 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.014 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.063 ║
║ Best                                9.644 ║
║ Worst                               0.000 ║
║ Total                               0.073 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.067 ║
║ Best                               11.101 ║
║ Worst                               0.000 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.042 ║
║ Best                               11.098 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.062 ║
║ Best                                8.814 ║
║ Worst                               0.000 ║
║ Total                               0.056 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.061 ║
║ Best                               11.582 ║
║ Worst                              -6.250 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.040 ║
║ Best                               11.482 ║
║ Worst                              -1.186 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                                8.795 ║
║ Best                                9.644 ║
║ Worst                               0.000 ║
║ Total                               9.105 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                3.421 ║
║ Best                               11.101 ║
║ Worst                               0.000 ║
║ Total                               8.697 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                3.303 ║
║ Best                               11.098 ║
║ Worst                               0.000 ║
║ Total                               0.808 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                7.106 ║
║ Best                                8.814 ║
║ Worst                               0.000 ║
║ Total                               7.434 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                3.535 ║
║ Best                               11.582 ║
║ Worst                               0.000 ║
║ Total                               9.197 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                3.368 ║
║ Best                               11.482 ║
║ Worst                               0.000 ║
║ Total                               0.880 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.026 ║
║ Best                                0.393 ║
║ Worst                               0.000 ║
║ Total                               0.033 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.006 ║
║ Best                                0.464 ║
║ Worst                               0.000 ║
║ Total                               0.006 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.089 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.036 ║
║ Best                                0.394 ║
║ Worst                               0.000 ║
║ Total                               0.056 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.004 ║
║ Best                                0.549 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.119 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.063 ║
║ Best                                9.644 ║
║ Worst                               0.000 ║
║ Total                               0.073 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.067 ║
║ Best                               11.101 ║
║ Worst                               0.000 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.042 ║
║ Best                               11.098 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.062 ║
║ Best                                8.814 ║
║ Worst                               0.000 ║
║ Total                               0.056 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.061 ║
║ Best                               11.582 ║
║ Worst                              -6.250 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.040 ║
║ Best                               11.482 ║
║ Worst                              -1.186 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                                8.795 ║
║ Best                                9.644 ║
║ Worst                               0.000 ║
║ Total                               9.105 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                3.421 ║
║ Best                               11.101 ║
║ Worst                               0.000 ║
║ Total                               8.697 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                3.303 ║
║ Best                               11.098 ║
║ Worst                               0.000 ║
║ Total                               0.808 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                7.106 ║
║ Best                                8.814 ║
║ Worst                               0.000 ║
║ Total                               7.434 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                3.535 ║
║ Best                               11.582 ║
║ Worst                               0.000 ║
║ Total                               9.197 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                3.368 ║
║ Best                               11.482 ║
║ Worst                               0.000 ║
║ Total                               0.880 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.026 ║
║ Best                                0.393 ║
║ Worst                               0.000 ║
║ Total                               0.033 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.006 ║
║ Best                                0.464 ║
║ Worst                               0.000 ║
║ Total                               0.006 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.089 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.036 ║
║ Best                                0.394 ║
║ Worst                               0.000 ║
║ Total                               0.056 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.004 ║
║ Best                                0.549 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.119 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by akiramenai** [comment]
It looks like https://github.com/matter-labs/compiler-llvm/pull/365 is superior to this. So closing.

**Pull request closed without merging**
