### PR TITLE
[WIP] Check ISelLowering methods from Pavel's patch on SyncVM

### PR DESCRIPTION
**Pull request by akiramenai**

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.000 ║
║ Best                                4.444 ║
║ Worst                              -5.128 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.000 ║
║ Best                                0.000 ║
║ Worst                              -1.818 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.001 ║
║ Best                                0.193 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.001 ║
║ Best                                4.444 ║
║ Worst                              -5.128 ║
║ Total                              -0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.003 ║
║ Best                                3.846 ║
║ Worst                              -5.128 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.002 ║
║ Best                                0.193 ║
║ Worst                              -0.113 ║
║ Total                               0.002 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by PavelKopyl** [comment]
By the way, could you, please, interpret that results? Am I right, that in a real life these patches reduce a code size only on 0.002%?

**Comment by PavelKopyl** [comment]
At some circumstances, 256-bit mask-like immediates (for example, 0xfffff....00000) are generated. They can be expressed via shifts + 8-bit immediates.

**Comment by PavelKopyl** [comment]
It's interesting, what is the test that gave  +5.128% code size?

**Comment by akiramenai** [comment]
@PavelKopyl  Yes, you're right.

**Comment by akiramenai** [comment]
As for +5.128% we might investigate it in future, but it's a low priority thing. If to take a look at the callosities of the methods, it looks clear why the effect is so negligible. Such patterns are rare in contracts. 5.128 is among simple tests and it might merely expose the very pattern and nothing else.

**Comment by akiramenai** [comment]
It looks like the methods don't affect numbers much, and we need more fine-tuned configuration of DAG ISel.

**Pull request closed without merging**
