### PR TITLE
[SyncVM] Tweak Loop Unroll parameters

### PR DESCRIPTION
**Pull request by vladimirradosavljevic**

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.384 ║
║ Best                               82.260 ║
║ Worst                             -177.143 ║
║ Total                               1.399 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.233 ║
║ Best                               15.873 ║
║ Worst                             -4540.476 ║
║ Total                              -0.086 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.127 ║
║ Best                               27.916 ║
║ Worst                             -2685.915 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.434 ║
║ Best                               25.950 ║
║ Worst                               0.000 ║
║ Total                               1.218 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.068 ║
║ Best                                0.000 ║
║ Worst                              -6.776 ║
║ Total                              -0.084 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                1.483 ║
║ Worst                              -0.193 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.412 ║
║ Best                               82.260 ║
║ Worst                             -137.143 ║
║ Total                               1.414 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.202 ║
║ Best                               15.873 ║
║ Worst                             -3880.952 ║
║ Total                              -0.058 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.107 ║
║ Best                               27.916 ║
║ Worst                             -2295.775 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.434 ║
║ Best                               25.950 ║
║ Worst                               0.000 ║
║ Total                               1.216 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.063 ║
║ Best                                0.000 ║
║ Worst                              -6.776 ║
║ Total                              -0.082 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                1.482 ║
║ Worst                              -0.193 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.175 ║
║ Best                               76.647 ║
║ Worst                             -97.143 ║
║ Total                               0.682 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.084 ║
║ Best                                8.065 ║
║ Worst                             -721.429 ║
║ Total                              -0.009 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.046 ║
║ Best                               27.916 ║
║ Worst                             -426.761 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by hedgar2017** [comment]
> Benchmark results:
> 
> ```
> ╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
> ║ Mean                                0.412 ║
> ║ Best                               82.260 ║
> ║ Worst                             -137.143 ║
> ║ Total                               1.414 ║
> ╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
> ║ Mean                               -0.202 ║
> ║ Best                               15.873 ║
> ║ Worst                             -3880.952 ║
> ║ Total                              -0.058 ║
> ╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
> ║ Mean                               -0.107 ║
> ║ Best                               27.916 ║
> ║ Worst                             -2295.775 ║
> ║ Total                              -0.000 ║
> ╚═══════════════════════════════════════════╝
> 
> ╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
> ║ Mean                                0.434 ║
> ║ Best                               25.950 ║
> ║ Worst                               0.000 ║
> ║ Total                               1.216 ║
> ╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
> ║ Mean                               -0.063 ║
> ║ Best                                0.000 ║
> ║ Worst                              -6.776 ║
> ║ Total                              -0.082 ║
> ╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
> ║ Mean                                0.002 ║
> ║ Best                                1.482 ║
> ║ Worst                              -0.193 ║
> ║ Total                               0.001 ║
> ╚═══════════════════════════════════════════╝
> ```

I'd keep this one.

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.232 ║
║ Best                               76.647 ║
║ Worst                             -75.862 ║
║ Total                               0.934 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.061 ║
║ Best                               10.159 ║
║ Worst                             -721.429 ║
║ Total                              -0.021 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.035 ║
║ Best                               27.916 ║
║ Worst                             -426.761 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.240 ║
║ Best                               19.397 ║
║ Worst                               0.000 ║
║ Total                               0.586 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.004 ║
║ Best                                0.000 ║
║ Worst                              -0.751 ║
║ Total                              -0.004 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.003 ║
║ Best                                0.894 ║
║ Worst                              -0.005 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.162 ║
║ Best                               76.647 ║
║ Worst                             -42.424 ║
║ Total                               0.609 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.031 ║
║ Best                               94.183 ║
║ Worst                             -365.370 ║
║ Total                              -0.018 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.011 ║
║ Best                               90.546 ║
║ Worst                             -292.990 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.205 ║
║ Best                               19.397 ║
║ Worst                               0.000 ║
║ Total                               0.480 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                0.629 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.056 ║
║ Best                               76.647 ║
║ Worst                             -34.234 ║
║ Total                               0.308 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.007 ║
║ Best                               25.762 ║
║ Worst                             -229.348 ║
║ Total                              -0.002 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.002 ║
║ Best                               31.720 ║
║ Worst                             -56.821 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.058 ║
║ Best                                2.703 ║
║ Worst                               0.000 ║
║ Total                               0.288 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.001 ║
║ Best                                0.000 ║
║ Worst                              -0.730 ║
║ Total                              -0.002 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.003 ║
║ Best                                0.894 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.129 ║
║ Best                               76.647 ║
║ Worst                             -62.857 ║
║ Total                               0.620 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.017 ║
║ Best                               16.889 ║
║ Worst                             -721.429 ║
║ Total                              -0.006 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.004 ║
║ Best                               30.166 ║
║ Worst                             -426.761 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.210 ║
║ Best                               19.397 ║
║ Worst                               0.000 ║
║ Total                               0.508 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.001 ║
║ Best                                0.000 ║
║ Worst                              -0.730 ║
║ Total                              -0.002 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.003 ║
║ Best                                0.894 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.098 ║
║ Best                               67.571 ║
║ Worst                             -48.329 ║
║ Total                               0.374 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.027 ║
║ Best                               10.159 ║
║ Worst                             -365.370 ║
║ Total                              -0.016 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.015 ║
║ Best                               26.781 ║
║ Worst                             -292.990 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.120 ║
║ Best                                4.723 ║
║ Worst                               0.000 ║
║ Total                               0.494 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.004 ║
║ Best                                0.000 ║
║ Worst                              -0.751 ║
║ Total                              -0.004 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.003 ║
║ Best                                0.894 ║
║ Worst                              -0.005 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.331 ║
║ Best                               76.647 ║
║ Worst                             -89.655 ║
║ Total                               1.280 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.097 ║
║ Best                               12.079 ║
║ Worst                             -994.118 ║
║ Total                              -0.026 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.055 ║
║ Best                               27.916 ║
║ Worst                             -535.092 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.317 ║
║ Best                               19.397 ║
║ Worst                               0.000 ║
║ Total                               0.892 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.039 ║
║ Best                                0.000 ║
║ Worst                              -5.333 ║
║ Total                              -0.038 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.003 ║
║ Best                                1.355 ║
║ Worst                              -0.328 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.297 ║
║ Best                               76.647 ║
║ Worst                             -75.862 ║
║ Total                               1.201 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.072 ║
║ Best                               12.360 ║
║ Worst                             -721.429 ║
║ Total                              -0.023 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.040 ║
║ Best                               27.916 ║
║ Worst                             -426.761 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.263 ║
║ Best                               19.397 ║
║ Worst                               0.000 ║
║ Total                               0.679 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.004 ║
║ Best                                0.000 ║
║ Worst                              -0.751 ║
║ Total                              -0.004 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.004 ║
║ Best                                1.050 ║
║ Worst                              -0.005 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.232 ║
║ Best                               76.647 ║
║ Worst                             -75.862 ║
║ Total                               0.934 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.061 ║
║ Best                               10.159 ║
║ Worst                             -721.429 ║
║ Total                              -0.021 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.035 ║
║ Best                               27.916 ║
║ Worst                             -426.761 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.240 ║
║ Best                               19.397 ║
║ Worst                               0.000 ║
║ Total                               0.586 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.004 ║
║ Best                                0.000 ║
║ Worst                              -0.751 ║
║ Total                              -0.004 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.003 ║
║ Best                                0.894 ║
║ Worst                              -0.005 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.366 ║
║ Best                               76.647 ║
║ Worst                             -89.655 ║
║ Total                               1.341 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.114 ║
║ Best                                8.989 ║
║ Worst                             -994.118 ║
║ Total                              -0.029 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.063 ║
║ Best                               27.916 ║
║ Worst                             -535.092 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.319 ║
║ Best                               19.397 ║
║ Worst                               0.000 ║
║ Total                               0.902 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.045 ║
║ Best                                0.000 ║
║ Worst                              -5.456 ║
║ Total                              -0.047 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.001 ║
║ Best                                0.930 ║
║ Worst                              -0.328 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.397 ║
║ Best                               82.260 ║
║ Worst                             -131.429 ║
║ Total                               1.400 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.143 ║
║ Best                               14.706 ║
║ Worst                             -2064.286 ║
║ Total                              -0.045 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.077 ║
║ Best                               27.916 ║
║ Worst                             -1221.127 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.408 ║
║ Best                               25.950 ║
║ Worst                               0.000 ║
║ Total                               1.092 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.053 ║
║ Best                                0.000 ║
║ Worst                              -6.018 ║
║ Total                              -0.054 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                1.232 ║
║ Worst                              -0.328 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.393 ║
║ Best                               82.260 ║
║ Worst                             -131.429 ║
║ Total                               1.393 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.128 ║
║ Best                                8.989 ║
║ Worst                             -2064.286 ║
║ Total                              -0.031 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.070 ║
║ Best                               27.916 ║
║ Worst                             -1221.127 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.383 ║
║ Best                               25.950 ║
║ Worst                               0.000 ║
║ Total                               0.998 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.046 ║
║ Best                                0.000 ║
║ Worst                              -5.456 ║
║ Total                              -0.048 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                1.035 ║
║ Worst                              -0.328 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by akiramenai** [comment]
We have it in #292 with slightly different values. Do we still need a separate PR for it?

**Comment by vladimirradosavljevic** [comment]
> We have it in #292 with slightly different values. Do we still need a separate PR for it?

This is no longer needed, as I used this PR to get the benchmark numbers only for the Loop Unroll change.

**Comment by hedgar2017** [comment]
> > We have it in #292 with slightly different values. Do we still need a separate PR for it?
> 
> 
> 
> This is no longer needed, as I used this PR to get the benchmark numbers only for the Loop Unroll change.

Don't forget to remove branches!

**Pull request closed without merging**
