### PR TITLE
[EraVM] Create new pass to split loop exits

### PR DESCRIPTION
**Pull request by vladimirradosavljevic**

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.001 ║
║ Best                                4.982 ║
║ Worst                              -5.774 ║
║ Total                               0.004 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.011 ║
║ Best                               32.725 ║
║ Worst                              -3.704 ║
║ Total                               0.009 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.007 ║
║ Best                               27.328 ║
║ Worst                              -0.312 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.006 ║
║ Best                                5.714 ║
║ Worst                              -8.602 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.009 ║
║ Best                               15.166 ║
║ Worst                             -18.471 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.007 ║
║ Best                               13.333 ║
║ Worst                             -10.991 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.012 ║
║ Best                                0.248 ║
║ Worst                              -0.142 ║
║ Total                               0.032 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.012 ║
║ Best                                0.860 ║
║ Worst                               0.000 ║
║ Total                               0.015 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.199 ║
║ Worst                              -0.001 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                               -0.003 ║
║ Best                                0.086 ║
║ Worst                              -0.638 ║
║ Total                              -0.002 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.494 ║
║ Worst                              -0.374 ║
║ Total                               0.003 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                               -0.000 ║
║ Best                                0.054 ║
║ Worst                              -0.121 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by akiramenai** [comment]
Rebased to double check numbers for this piece standalone.

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                4.982 ║
║ Worst                              -5.774 ║
║ Total                               0.004 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.011 ║
║ Best                               32.725 ║
║ Worst                              -3.704 ║
║ Total                               0.009 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.007 ║
║ Best                               27.328 ║
║ Worst                              -0.312 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.006 ║
║ Best                                5.714 ║
║ Worst                              -5.128 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.010 ║
║ Best                               15.166 ║
║ Worst                             -18.471 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.007 ║
║ Best                               13.333 ║
║ Worst                              -8.500 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.012 ║
║ Best                                0.248 ║
║ Worst                               0.000 ║
║ Total                               0.031 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.012 ║
║ Best                                0.860 ║
║ Worst                               0.000 ║
║ Total                               0.015 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.200 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                               -0.002 ║
║ Best                                0.151 ║
║ Worst                              -0.638 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                               -0.000 ║
║ Best                                0.275 ║
║ Worst                              -0.624 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                               -0.001 ║
║ Best                                0.003 ║
║ Worst                              -0.195 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by vladimirradosavljevic** [comment]
Closing it since it has negligible impact on the performance.

**Pull request closed without merging**
