### PR TITLE
[WIP] Enable GVNHoist Pass

### PR DESCRIPTION
**Pull request by lialan**
Try out GVNHoist to see its impact on sizes and cycles

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.083 ║
║ Best                                5.128 ║
║ Worst                              -2.353 ║
║ Total                               0.084 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                2.439 ║
║ Worst                              -7.042 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                1.609 ║
║ Worst                              -6.224 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.124 ║
║ Best                                1.278 ║
║ Worst                               0.000 ║
║ Total                               0.162 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.022 ║
║ Best                                1.059 ║
║ Worst                              -1.852 ║
║ Total                               0.233 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.006 ║
║ Best                                0.579 ║
║ Worst                              -0.863 ║
║ Total                               0.006 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.083 ║
║ Best                                5.128 ║
║ Worst                              -2.353 ║
║ Total                               0.084 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                2.439 ║
║ Worst                              -7.042 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                1.609 ║
║ Worst                              -6.224 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.124 ║
║ Best                                1.278 ║
║ Worst                               0.000 ║
║ Total                               0.162 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.022 ║
║ Best                                1.059 ║
║ Worst                              -1.852 ║
║ Total                               0.233 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.006 ║
║ Best                                0.579 ║
║ Worst                              -0.863 ║
║ Total                               0.006 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.083 ║
║ Best                                5.128 ║
║ Worst                              -2.353 ║
║ Total                               0.084 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                2.632 ║
║ Worst                              -7.042 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                1.818 ║
║ Worst                              -6.224 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.124 ║
║ Best                                1.278 ║
║ Worst                               0.000 ║
║ Total                               0.166 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.022 ║
║ Best                                1.059 ║
║ Worst                              -1.852 ║
║ Total                               0.233 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.006 ║
║ Best                                0.579 ║
║ Worst                              -0.863 ║
║ Total                               0.006 ║
╚═══════════════════════════════════════════╝

```

**Comment by akiramenai** [comment]
Integrated to #260, thank you!

**Pull request closed without merging**
