### PR TITLE
enable logic in simplifyCondBranch

### PR DESCRIPTION
**Pull request by akiramenai**

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                               -0.351 ║
║ Best                               25.160 ║
║ Worst                             -34.286 ║
║ Total                              -0.581 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.302 ║
║ Best                               65.385 ║
║ Worst                             -570.000 ║
║ Total                               0.014 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.131 ║
║ Best                               54.138 ║
║ Worst                             -289.831 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                               -0.016 ║
║ Best                               14.332 ║
║ Worst                             -31.515 ║
║ Total                              -0.021 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                               -0.001 ║
║ Best                               60.000 ║
║ Worst                             -215.789 ║
║ Total                              -0.005 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                               -0.003 ║
║ Best                               46.452 ║
║ Worst                             -110.314 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.018 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.018 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                               -0.536 ║
║ Best                                1.646 ║
║ Worst                              -2.617 ║
║ Total                              -0.521 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                2.175 ║
║ Best                               32.258 ║
║ Worst                             -19.048 ║
║ Total                               0.198 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.426 ║
║ Best                               12.448 ║
║ Worst                              -6.316 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.034 ║
║ Best                                0.619 ║
║ Worst                              -2.597 ║
║ Total                              -0.043 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.688 ║
║ Best                               36.508 ║
║ Worst                             -21.739 ║
║ Total                              -0.053 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                               -0.114 ║
║ Best                                8.824 ║
║ Worst                              -7.653 ║
║ Total                              -0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                               -0.351 ║
║ Best                               25.160 ║
║ Worst                             -34.286 ║
║ Total                              -0.581 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.302 ║
║ Best                               65.385 ║
║ Worst                             -570.000 ║
║ Total                               0.014 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.131 ║
║ Best                               54.138 ║
║ Worst                             -289.831 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                               -0.016 ║
║ Best                               14.332 ║
║ Worst                             -31.515 ║
║ Total                              -0.021 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                               -0.001 ║
║ Best                               60.000 ║
║ Worst                             -215.789 ║
║ Total                              -0.005 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                               -0.003 ║
║ Best                               46.452 ║
║ Worst                             -110.314 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.018 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.018 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                               -0.536 ║
║ Best                                1.646 ║
║ Worst                              -2.617 ║
║ Total                              -0.521 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                2.175 ║
║ Best                               32.258 ║
║ Worst                             -19.048 ║
║ Total                               0.198 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.426 ║
║ Best                               12.448 ║
║ Worst                              -6.316 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.034 ║
║ Best                                0.619 ║
║ Worst                              -2.597 ║
║ Total                              -0.043 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.688 ║
║ Best                               36.508 ║
║ Worst                             -21.739 ║
║ Total                              -0.053 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                               -0.114 ║
║ Best                                8.824 ║
║ Worst                              -7.653 ║
║ Total                              -0.001 ║
╚═══════════════════════════════════════════╝

```

**Comment by hedgar2017** [comment]
This tradeoff is ok.

**Review by PavelKopyl — APPROVED** [review]
Could you please, recall, why that functionality was early disabled?
LGTM.

**Pull request merged**
