### PR TITLE
ci: support regression tests on all platforms

### PR DESCRIPTION
**Pull request by antonbaliasnikov**
# Code Review Checklist

* [x] Support periodical llvm-lit regression tests on all supported platforms.
* [x] Disable unsupported tests on Windows
* [x] Add Slack notification if periodic run fails
* [x] Add capability to enable/disable assertions 

## Tests

[Testing workflow](https://github.com/matter-labs/era-compiler-llvm/actions/runs/10813828966)

### CODE REVIEW

**Review by hedgar2017 — APPROVED** [review]

**Comment by hedgar2017** [comment]
The CI was skipped.
Was everything OK?

**Comment by akiramenai** [comment]
I had a similar issue with https://github.com/matter-labs/era-compiler-llvm/pull/701 and had to run tests manually.

**Comment by antonbaliasnikov** [comment]
> I had a similar issue with #701 and had to run tests manually.

@akiramenai , this can be caused by conflicts between `main` and your branch. After you fix conflicts, CI will start.

**Comment by antonbaliasnikov** [comment]
> The CI was skipped. Was everything OK?

Yeah, the thing is that I did not touch the workflow that is running in pull requests, I've added manual and scheduled runs.

That's why I've created a special section for testing workflow:
[Testing workflow](https://github.com/matter-labs/era-compiler-llvm/actions/runs/10813828966)

**Pull request merged**
