### PR TITLE
[EraVM] Implement __system_request_slice_fallback

### PR DESCRIPTION
**Pull request by vladimirradosavljevic**
This implementation is similar to __system_request, but without the initial 4 bytes for the signature, and returns a whole slice.

### CODE REVIEW

**Review by hedgar2017 — APPROVED** [review]

**Comment by vladimirradosavljevic** [comment]
Since we disabled CSE in GVN and NewGVN, running EraVMCSE later in the pipeline should fix these degradations.

**Review by hedgar2017 — CHANGES_REQUESTED** [review]
Oh lawd, sorry, I was slightly wrong about this `@__system_request_fallback`!

It must return the pointer it receives from the underlying call, that is `system_request_result_abi_data`, since the call returns not a single value, but the whole slice!

Let's also rename it to `@__system_request_slice_fallback`, as we may have all 4 combinations in the future.

**Comment by vladimirradosavljevic** [comment]
> Oh lawd, sorry, I was slightly wrong about this `@__system_request_fallback`!
> 
> It must return the pointer it receives from the underlying call, that is `system_request_result_abi_data`, since the call returns not a single value, but the whole slice!
> 
> Let's also rename it to `@__system_request_slice_fallback`, as we may have all 4 combinations in the future.

Done. Changed the name to `@__system_request_slice_fallback` and this function returns whole slice (`system_request_result_abi_data`).

**Review by hedgar2017 — APPROVED** [review]
Thanks!
Please merge.

**Review by akiramenai — APPROVED** [review]

**Comment by akiramenai** [comment]
Only changed comments, so merging.

**Pull request merged**
