### PR TITLE
[DO NOT MERGE] hint RA coalescing using optimizeSelect

### PR DESCRIPTION
**Pull request by lialan**
as seen in Lanai. If this still cannot get around the verifier then we have to go the ugly approach.

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.129 ║
║ Best                                7.407 ║
║ Worst                              -7.018 ║
║ Total                               0.071 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.162 ║
║ Best                                7.317 ║
║ Worst                             -14.097 ║
║ Total                               0.038 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.052 ║
║ Best                                4.967 ║
║ Worst                             -13.469 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.142 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.171 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.196 ║
║ Best                                8.791 ║
║ Worst                             -12.449 ║
║ Total                               0.038 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.067 ║
║ Best                                6.498 ║
║ Worst                             -10.512 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                               -0.002 ║
║ Best                                0.466 ║
║ Worst                              -0.360 ║
║ Total                               0.035 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.051 ║
║ Best                                0.433 ║
║ Worst                              -0.155 ║
║ Total                               0.033 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.032 ║
║ Worst                              -0.127 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.086 ║
║ Best                                0.768 ║
║ Worst                               0.000 ║
║ Total                               0.118 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.448 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.236 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.074 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.006 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.131 ║
║ Best                                7.407 ║
║ Worst                              -7.018 ║
║ Total                               0.074 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.166 ║
║ Best                                7.317 ║
║ Worst                             -14.097 ║
║ Total                               0.039 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.054 ║
║ Best                                4.967 ║
║ Worst                             -13.469 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.145 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.176 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.201 ║
║ Best                                8.791 ║
║ Worst                             -12.449 ║
║ Total                               0.039 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.070 ║
║ Best                                6.498 ║
║ Worst                             -10.512 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.003 ║
║ Best                                0.480 ║
║ Worst                              -0.360 ║
║ Total                               0.041 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.060 ║
║ Best                                0.433 ║
║ Worst                               0.000 ║
║ Total                               0.070 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.036 ║
║ Worst                              -0.127 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.090 ║
║ Best                                0.768 ║
║ Worst                              -0.087 ║
║ Total                               0.126 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.466 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.275 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.075 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.135 ║
║ Best                                7.407 ║
║ Worst                              -7.018 ║
║ Total                               0.076 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.168 ║
║ Best                                7.317 ║
║ Worst                             -14.097 ║
║ Total                               0.039 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.055 ║
║ Best                                4.967 ║
║ Worst                             -13.469 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.145 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.176 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.202 ║
║ Best                                8.791 ║
║ Worst                             -12.449 ║
║ Total                               0.039 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.070 ║
║ Best                                6.498 ║
║ Worst                             -10.512 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.003 ║
║ Best                                0.480 ║
║ Worst                              -0.360 ║
║ Total                               0.041 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.060 ║
║ Best                                0.433 ║
║ Worst                               0.000 ║
║ Total                               0.070 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.036 ║
║ Worst                              -0.127 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.090 ║
║ Best                                0.768 ║
║ Worst                              -0.087 ║
║ Total                               0.126 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.466 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.275 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.075 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.135 ║
║ Best                                7.407 ║
║ Worst                              -7.018 ║
║ Total                               0.076 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.168 ║
║ Best                                7.317 ║
║ Worst                             -14.097 ║
║ Total                               0.039 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.055 ║
║ Best                                4.967 ║
║ Worst                             -13.469 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.145 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.176 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.202 ║
║ Best                                8.791 ║
║ Worst                             -12.449 ║
║ Total                               0.039 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.070 ║
║ Best                                6.498 ║
║ Worst                             -10.512 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.003 ║
║ Best                                0.480 ║
║ Worst                              -0.360 ║
║ Total                               0.041 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.060 ║
║ Best                                0.433 ║
║ Worst                               0.000 ║
║ Total                               0.070 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.036 ║
║ Worst                              -0.127 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.090 ║
║ Best                                0.768 ║
║ Worst                              -0.087 ║
║ Total                               0.126 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.466 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.275 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.075 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

```

**Comment by lialan** [comment]
not very helpful compared to #317 so closing it.

**Pull request closed without merging**
