### PR TITLE
[SyncVM] Add 'minsize' and 'optforsize' attributes to all functions.

### PR DESCRIPTION
**Pull request by PavelKopyl**

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.009 ║
║ Best                                2.410 ║
║ Worst                               0.000 ║
║ Total                               0.009 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                3.115 ║
║ Worst                              -2.655 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                2.151 ║
║ Worst                              -2.521 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.006 ║
║ Best                                0.499 ║
║ Worst                               0.000 ║
║ Total                               0.006 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.061 ║
║ Best                                3.115 ║
║ Worst                              -0.266 ║
║ Total                               0.977 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.012 ║
║ Best                                1.781 ║
║ Worst                              -0.005 ║
║ Total                               0.024 ║
╚═══════════════════════════════════════════╝

```

**Comment by hedgar2017** [comment]
The benchmark is funny. Should've decreased size but decreased cycles.

**Comment by PavelKopyl** [comment]
> The benchmark is funny. Should've decreased size but decreased cycles.

Yep. Unfortunately it's a typical situation in the LLVM IR pipeline, as passes influence each other and the final may be unexpected. Of course we can track down what is happening exactly, but I think that is fine as long as we do not get regressions.

**Comment by hedgar2017** [comment]
> > The benchmark is funny. Should've decreased size but decreased cycles.
> 
> 
> 
> Yep. Unfortunately it's a typical situation in the LLVM IR pipeline, as passes influence each other and the final may be unexpected. Of course we can track down what is happening exactly, but I think that is fine as long as we do not get regressions.

Sure.
It will be more funny if we turn it on for M3 and improve even more.

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.009 ║
║ Best                                2.410 ║
║ Worst                               0.000 ║
║ Total                               0.009 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                3.115 ║
║ Worst                              -2.655 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                2.151 ║
║ Worst                              -2.521 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.006 ║
║ Best                                0.499 ║
║ Worst                               0.000 ║
║ Total                               0.006 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.061 ║
║ Best                                3.115 ║
║ Worst                              -0.266 ║
║ Total                               0.977 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.012 ║
║ Best                                1.781 ║
║ Worst                              -0.005 ║
║ Total                               0.024 ║
╚═══════════════════════════════════════════╝

```

**Comment by PavelKopyl** [comment]
> > > The benchmark is funny. Should've decreased size but decreased cycles.
> > 
> > 
> > Yep. Unfortunately it's a typical situation in the LLVM IR pipeline, as passes influence each other and the final may be unexpected. Of course we can track down what is happening exactly, but I think that is fine as long as we do not get regressions.
> 
> Sure. It will be more funny if we turn it on for M3 and improve even more.


I'll try, that's easy)

**Comment by PavelKopyl** [comment]
This functionality was merged in along with https://github.com/matter-labs/compiler-llvm/pull/291

**Comment by hedgar2017** [comment]
> This functionality was merged in along with https://github.com/matter-labs/compiler-llvm/pull/291

Please remove branches when closing a PR.

**Pull request closed without merging**
