### PR TITLE
Upstream werror fixes

### PR DESCRIPTION
**Pull request by akiramenai**

### CODE REVIEW

**Review by antonbaliasnikov — COMMENTED** [review]
@akiramenai , clang-tidy is unhappy with static by some reason :(

**Comment by akiramenai** [comment]
@antonbaliasnikov upstream doesn't use the same settings as we are, so `clang-tidy` was never a blocker for cherry-picks. Introducing local changes is more detrimental than making the linter happy.
So, I'd suggest merging if you checked that it indeed fixes the problem.

**Comment by antonbaliasnikov** [comment]
> @antonbaliasnikov upstream doesn't use the same settings as we are, so `clang-tidy` was never a blocker for cherry-picks. Introducing local changes is more detrimental than making the linter happy. So, I'd suggest merging if you checked that it indeed fixes the problem.

@akiramenai ,
Got you. I've built this branch and disabled `WError` completely, and there are more warnings about unused variables.
_I'm sorry I did not do it yesterday to get the full list of errors and got only the first two._

Can you, please, take a look:
```
[740/2421] Building CXX object lib/Bitcode/Reader/CMakeFiles/LLVMBitReader.dir/MetadataLoader.cpp.o
/era-compiler-solidity/llvm/llvm/lib/Bitcode/Reader/MetadataLoader.cpp:563:23: warning: variable 'S' set but not used [-Wunused-but-set-variable]
  563 |             if (auto *S = dyn_cast_or_null<DILocalScope>(IE->getScope())) {
      |                       ^
/era-compiler-solidity/llvm/llvm/lib/Bitcode/Reader/MetadataLoader.cpp:558:19: warning: variable 'RawImported' set but not used [-Wunused-but-set-variable]
  558 |         if (auto *RawImported = CU->getRawImportedEntities()) {
      |                   ^
2 warnings generated.
[767/2421] Building CXX object lib/Transforms/Utils/CMakeFiles/LLVMTransformUtils.dir/BasicBlockUtils.cpp.o
/era-compiler-solidity/llvm/llvm/lib/Transforms/Utils/BasicBlockUtils.cpp:638:19: warning: variable 'SP' set but not used [-Wunused-but-set-variable]
  638 |   if (BasicBlock *SP = Succ->getSinglePredecessor()) {
      |                   ^
1 warning generated.
[892/2421] Building CXX object lib/Transforms/Scalar/CMakeFiles/LLVMScalarOpts.dir/EarlyCSE.cpp.o
/era-compiler-solidity/llvm/llvm/lib/Transforms/Scalar/EarlyCSE.cpp:1448:17: warning: variable 'CI' set but not used [-Wunused-but-set-variable]
 1448 |       if (auto *CI = dyn_cast<ConstrainedFPIntrinsic>(&Inst)) {
      |                 ^
1 warning generated.
[943/2421] Building CXX object lib/Transforms/Scalar/CMakeFiles/LLVMScalarOpts.dir/Scalarizer.cpp.o
/era-compiler-solidity/llvm/llvm/lib/Transforms/Scalar/Scalarizer.cpp:733:15: warning: variable 'OpVecTy' set but not used [-Wunused-but-set-variable]
  733 |     if (auto *OpVecTy = dyn_cast<FixedVectorType>(OpI->getType())) {
      |               ^
1 warning generated.
[1658/2421] Building CXX object lib/Target/EraVM/CMakeFiles/LLVMEraVMCodeGen.dir/EraVMAliasAnalysis.cpp.o
/era-compiler-solidity/llvm/llvm/lib/Target/EraVM/EraVMAliasAnalysis.cpp:107:19: warning: variable 'CPN' set but not used [-Wunused-but-set-variable]
  107 |   if (const auto *CPN = dyn_cast<ConstantPointerNull>(Loc.Ptr))
      |                   ^
1 warning generated.
[1675/2421] Building CXX object lib/Target/EraVM/CMakeFiles/LLVMEraVMCodeGen.dir/EraVMISelDAGToDAG.cpp.o
/era-compiler-solidity/llvm/llvm/lib/Target/EraVM/EraVMISelDAGToDAG.cpp:232:16: warning: variable 'Unaligned' set but not used [-Wunused-but-set-variable]
  232 |   if (unsigned Unaligned = AM.Disp % 32) {
      |                ^
1 warning generated.
[1678/2421] Building CXX object lib/Target/EraVM/CMakeFiles/LLVMEraVMCodeGen.dir/EraVMAsmPrinter.cpp.o
/era-compiler-solidity/llvm/llvm/lib/Target/EraVM/EraVMAsmPrinter.cpp:371:19: warning: variable 'V' set but not used [-Wunused-but-set-variable]
  371 |   if (const auto *V = dyn_cast<ConstantVector>(CV)) {
      |                   ^
/era-compiler-solidity/llvm/llvm/lib/Target/EraVM/EraVMAsmPrinter.cpp:376:19: warning: variable 'CE' set but not used [-Wunused-but-set-variable]
  376 |   if (const auto *CE = dyn_cast<ConstantExpr>(CV))
      |                   ^
2 warnings generated.
[1685/2421] Building CXX object lib/Target/EraVM/CMakeFiles/LLVMEraVMCodeGen.dir/EraVMISelLowering.cpp.o
/era-compiler-solidity/llvm/llvm/lib/Target/EraVM/EraVMISelLowering.cpp:507:18: warning: variable 'E' set but not used [-Wunused-but-set-variable]
  507 |   else if (auto *E = dyn_cast<ExternalSymbolSDNode>(Callee))
      |                  ^
/era-compiler-solidity/llvm/llvm/lib/Target/EraVM/EraVMISelLowering.cpp:505:13: warning: variable 'G' set but not used [-Wunused-but-set-variable]
  505 |   if (auto *G = dyn_cast<GlobalAddressSDNode>(Callee))
      |             ^
/era-compiler-solidity/llvm/llvm/lib/Target/EraVM/EraVMISelLowering.cpp:547:19: warning: variable 'Invoke' set but not used [-Wunused-but-set-variable]
  547 |   if (const auto *Invoke = dyn_cast_or_null<InvokeInst>(CLI.CB))
      |                   ^
3 warnings generated.
[1742/2421] Building CXX object lib/Target/EVM/CMakeFiles/LLVMEVMCodeGen.dir/EVMStackify.cpp.o
/era-compiler-solidity/llvm/llvm/lib/Target/EVM/EVMStackify.cpp:706:19: warning: variable 'BB' set but not used [-Wunused-but-set-variable]
  706 |   if (const auto *BB = LIS.intervalIsInOneMBB(*LI))
      |                   ^
/era-compiler-solidity/llvm/llvm/lib/Target/EVM/EVMStackify.cpp:1239:21: warning: variable 'BB' set but not used [-Wunused-but-set-variable]
 1239 |     if (const auto *BB = LIS.intervalIsInOneMBB(*LI)) {
      |                     ^
2 warnings generated.
```

**Review by antonbaliasnikov — APPROVED** [review]
@akiramenai , I cherry-picked some more upstream fixes and tested. It works now. Please, check when you have a second.

**Comment by akiramenai** [comment]
@antonbaliasnikov thank you.

**Pull request merged**
