### PR TITLE
[EraVM] Change __addmod implementation

### PR DESCRIPTION
**Pull request by vladimirradosavljevic**

### CODE REVIEW

**Review by akiramenai — APPROVED** [review]
LGTM,
But if we can add a minimal test that shows perf improvement it would be better.

**Comment by vladimirradosavljevic** [comment]
> LGTM, But if we can add a minimal test that shows perf improvement it would be better.

Creating test from `p256verify` precompile will be hard, so my suggestion is to wait for the results and maybe we will be lucky to find a small test that shows performance improvement.

**Comment by akiramenai** [comment]
@vladimirradosavljevic please create a follow up ticket to dig into perf regressions on real life group.

**Comment by vladimirradosavljevic** [comment]
@akiramenai This should fix regressions in real life and numbers in p256verify should stay the same.

**Comment by vladimirradosavljevic** [comment]
@akiramenai I managed to create the minimal test to show perf improvement. It turns out that with the new implementation, ISel optimizations are able to remove one select instruction.

**Pull request merged**
