### PR TITLE
 Change the __sha3 offset argument to a pointer

### PR DESCRIPTION
**Pull request by PavelKopyl**

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.451 ║
║ Best                               27.160 ║
║ Worst                             -37.838 ║
║ Total                              -0.488 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                               76.433 ║
║ Worst                             -25.333 ║
║ Total                              -0.310 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.103 ║
║ Best                               28.630 ║
║ Worst                              -9.947 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -1.452 ║
║ Best                                0.000 ║
║ Worst                             -11.921 ║
║ Total                              -1.069 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -2.946 ║
║ Best                                0.000 ║
║ Worst                             -17.751 ║
║ Total                              -0.986 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.672 ║
║ Best                                0.000 ║
║ Worst                              -8.523 ║
║ Total                              -0.031 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.451 ║
║ Best                               27.160 ║
║ Worst                             -37.838 ║
║ Total                              -0.488 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                               76.433 ║
║ Worst                             -25.333 ║
║ Total                              -0.310 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.103 ║
║ Best                               28.630 ║
║ Worst                              -9.947 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -1.452 ║
║ Best                                0.000 ║
║ Worst                             -11.921 ║
║ Total                              -1.069 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -2.946 ║
║ Best                                0.000 ║
║ Worst                             -17.751 ║
║ Total                              -0.986 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.672 ║
║ Best                                0.000 ║
║ Worst                              -8.523 ║
║ Total                              -0.031 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.330 ║
║ Best                               32.099 ║
║ Worst                             -37.838 ║
║ Total                              -0.393 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                               77.282 ║
║ Worst                             -25.336 ║
║ Total                              -0.306 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.099 ║
║ Best                               32.499 ║
║ Worst                             -10.267 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -1.391 ║
║ Best                                4.174 ║
║ Worst                             -10.738 ║
║ Total                              -1.035 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -2.060 ║
║ Best                               23.134 ║
║ Worst                             -17.073 ║
║ Total                              -0.750 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.619 ║
║ Best                                0.179 ║
║ Worst                              -8.103 ║
║ Total                              -0.022 ║
╚═══════════════════════════════════════════╝

```

**Comment by PavelKopyl** [comment]
Please, ignore benchmark results posted here, as for real testing we need corresponding FE changes. Please see the actual results here: https://github.com/matter-labs/compiler-tester/pull/322

**Review by hedgar2017 — APPROVED** [review]

**Review by akiramenai — APPROVED** [review]

**Pull request merged**
