### PR TITLE
[EraVM] Add freeze before use of first argument in __addmod

### PR DESCRIPTION
**Pull request by vladimirradosavljevic**

### CODE REVIEW

**Comment by vladimirradosavljevic** [comment]
Alive2 before freeze: https://alive2.llvm.org/ce/z/73AsFT
Alive2 after freeze: https://alive2.llvm.org/ce/z/G9nKaA

**Comment by FlashSheridan** [comment]
The freeze seems the correct way to avoid the problem of optimizing one use of %arg1m into multiple uses.  So LGTM, but I don’t know enough of the context for a formal approval.

**Review by akiramenai — APPROVED** [review]
LGTM

**Review by PavelKopyl — APPROVED** [review]
LGTM.

**Review by hedgar2017 — APPROVED** [review]

**Comment by hedgar2017** [comment]
@vladimirradosavljevic can it be done in other places, `__mulmod` as the closest one?

**Comment by vladimirradosavljevic** [comment]
@hedgar2017 In case we changed implementations from using overflow intrinsics to other non-overflow instructions, we should add them in alive2 to verify. Currently, I'm not sure whether we have to add freeze instruction in other implementations.

**Pull request merged**
