### PR TITLE
[EraVM][MC] Define static read/write instructions

### LINKED ISSUE #457: [MC] Implement static read / write

### PR DESCRIPTION
**Pull request by atrosinenko**
Define the new static read/write instructions:
    
        ldm.st, ldmi.st, stm.st, stmi.st

### CODE REVIEW

**Review by asl — APPROVED** [review]

**Comment by atrosinenko** [comment]
@sayon Could you please look at the tests?

**Comment by atrosinenko** [comment]
This patch is ready to merge assuming the encoding is correct.

**Comment by atrosinenko** [comment]
Stacked this PR on top of #563 as alias removal was moved there.

**Review by sayon — APPROVED** [review]
This is good to me. Thank you!

**Pull request merged**
