### PR TITLE
[EraVM] Enable MachineCopyPropagation optimization

### PR DESCRIPTION
**Pull request by vladimirradosavljevic**
This PR enables MachineCopyPropagation for EraVM (by adding `let AllowRegisterRenaming = 1` in `EraVM.td`), cherry-picks some improvements and adds some more improvements.

### CODE REVIEW

**Comment by vladimirradosavljevic** [comment]
One regression test is failing for https://github.com/matter-labs/era-compiler-llvm/pull/712/commits/20c39f64140dd503801e3e2ea7be802921de5600 commit, since it introduces two parameters in `copyPhysReg` function and we are applying this in EVM and EraVM in the following commit.
I'm not sure whether we can make CI fully happy since we are doing cherry-pick from the upstream and in the next commit we are adding that to our backends.

**Comment by akiramenai** [comment]
Theoretically, we could use a pre-commit XFAIL and re-enable it later, but since we periodically update LLVM and rebase our commits on top of theirs, I recommend not worrying about it. We have admin privileges to bypass the CI if needed.

**Review by akiramenai — APPROVED** [review]
Could we add tests to
`[EraVM][EVM] Add renamable bit to copyPhysReg`
`[EraVM] Enable MachineCopyPropagation optimization`.
Also links to upstream counterparts in the commit messages are very welcome for future LLVM updates.

**Comment by vladimirradosavljevic** [comment]
> Could we add tests to `[EraVM] Enable MachineCopyPropagation optimization`.

This is the name of the PR, and there is no such commit. Did you have some other commit in your mind?

> Also links to upstream counterparts in the commit messages are very welcome for future LLVM updates.

This is for https://github.com/matter-labs/era-compiler-llvm/pull/712/commits/c8750aa016171e60ae48dec4f208dae05058b06a and https://github.com/matter-labs/era-compiler-llvm/pull/712/commits/b653cb6e4eb9f3e28caaf929153259f1320b2091, right?

**Comment by akiramenai** [comment]
@vladimirradosavljevic Sorry, this one: `[EraVM] Enable MachineCopyPropagation optimization`

**Comment by akiramenai** [comment]
> This is for https://github.com/matter-labs/era-compiler-llvm/commit/c8750aa016171e60ae48dec4f208dae05058b06a and https://github.com/matter-labs/era-compiler-llvm/commit/b653cb6e4eb9f3e28caaf929153259f1320b2091, right?

Yes, to make checking their status easier.

**Comment by vladimirradosavljevic** [comment]
> @vladimirradosavljevic Sorry, this one: `[EraVM] Enable MachineCopyPropagation optimization`

Copy paste typo. Did you mean `[EraVM] Set AllowRegisterRenaming to 1`?

**Comment by vladimirradosavljevic** [comment]
Added test for `[EraVM][EVM] Add renamable bit to copyPhysReg`. Needed to reorganize commits, since to test this, we first need to do https://github.com/matter-labs/era-compiler-llvm/pull/712/commits/d34e85b26a553bf0a6ae4f853e327932de73ea86.
Added test for `[EraVM] Set AllowRegisterRenaming to 1` and added links to upstream PRs.
@akiramenai PTAL.

**Review by akiramenai — COMMENTED** [review]
LGTM, thanks!
Will wait for the rest of the checkers and then merge.

**Pull request merged**
