### PR TITLE
[EraVM] Enable jump tables

### PR DESCRIPTION
**Pull request by vladimirradosavljevic**

### CODE REVIEW

**Review by akiramenai — APPROVED** [review]
LGTM, thanks

**Review by akiramenai — APPROVED** [review]
LGTM, thanks

**Comment by akiramenai** [comment]
Better is to squash

**Comment by vladimirradosavljevic** [comment]
@akiramenai What do you think about only squashing test and predicate fix? I think we should at least keep 3 commits
1. For easier LLVM rebase.
2. JT support.
3. isPredicate implementation for easier understanding of the implementation, and not as part of the JT support.

Does it make sense to you?

**Review by hedgar2017 — CHANGES_REQUESTED** [review]
Could you rename the CLI arg to `-eravm-jump-table-density-threshold`?

**Comment by vladimirradosavljevic** [comment]
> Could you rename the CLI arg to `-eravm-jump-table-density-threshold`?

Common LLVM option is called `-jump-table-density`, so I took the naming from there and just added `era` prefix. Is there a particular reason why we need `-eravm-jump-table-density-threshold`?

**Comment by hedgar2017** [comment]
> > Could you rename the CLI arg to `-eravm-jump-table-density-threshold`?
> 
> Common LLVM option is called `-jump-table-density`, so I took the naming from there and just added `era` prefix. Is there a particular reason why we need `-eravm-jump-table-density-threshold`?

In Slack you mentioned `-era-jump-table-density`, neither nothing nor `-era`. Could we unify?

**Comment by vladimirradosavljevic** [comment]
> > > Could you rename the CLI arg to `-eravm-jump-table-density-threshold`?
> > 
> > 
> > Common LLVM option is called `-jump-table-density`, so I took the naming from there and just added `era` prefix. Is there a particular reason why we need `-eravm-jump-table-density-threshold`?
> 
> In Slack you mentioned `-era-jump-table-density`, neither nothing nor `-era`. Could we unify?

Sorry for the confusion, option I have added is called `-eravm-jump-table-density` and what I said is that I took naming from the common llvm option that is called `-jump-table-density`. Of course I can change it to `-eravm-jump-table-density-threshold`, but I just wanted to know the reason behind it.

**Comment by hedgar2017** [comment]
> > > > Could you rename the CLI arg to `-eravm-jump-table-density-threshold`?
> > > 
> > > 
> > > Common LLVM option is called `-jump-table-density`, so I took the naming from there and just added `era` prefix. Is there a particular reason why we need `-eravm-jump-table-density-threshold`?
> > 
> > 
> > In Slack you mentioned `-era-jump-table-density`, neither nothing nor `-era`. Could we unify?
> 
> Sorry for the confusion, option I have added is called `-eravm-jump-table-density` and what I said is that I took naming from the common llvm option that is called `-jump-table-density`. Of course I can change it to `-eravm-jump-table-density-threshold`, but I just wanted to know the reason behind it.

So should we keep `-jump-table-density` or do we need this `-eravm` prefix?
If the latter, I prefer a more complete key `-eravm-jump-table-density-threshold`. If the former, let's just reuse the one already available.

**Comment by vladimirradosavljevic** [comment]
> > > > > Could you rename the CLI arg to `-eravm-jump-table-density-threshold`?
> > > > 
> > > > 
> > > > Common LLVM option is called `-jump-table-density`, so I took the naming from there and just added `era` prefix. Is there a particular reason why we need `-eravm-jump-table-density-threshold`?
> > > 
> > > 
> > > In Slack you mentioned `-era-jump-table-density`, neither nothing nor `-era`. Could we unify?
> > 
> > 
> > Sorry for the confusion, option I have added is called `-eravm-jump-table-density` and what I said is that I took naming from the common llvm option that is called `-jump-table-density`. Of course I can change it to `-eravm-jump-table-density-threshold`, but I just wanted to know the reason behind it.
> 
> So should we keep `-jump-table-density` or do we need this `-eravm` prefix? If the latter, I prefer a more complete key `-eravm-jump-table-density-threshold`. If the former, let's just reuse the one already available.

We introduced new custom option to reduce local changes, so yes latter is preferable. I will rename it to `-eravm-jump-table-density-threshold`.

**Comment by hedgar2017** [comment]
> > > > > > Could you rename the CLI arg to `-eravm-jump-table-density-threshold`?
> > > > > 
> > > > > 
> > > > > Common LLVM option is called `-jump-table-density`, so I took the naming from there and just added `era` prefix. Is there a particular reason why we need `-eravm-jump-table-density-threshold`?
> > > > 
> > > > 
> > > > In Slack you mentioned `-era-jump-table-density`, neither nothing nor `-era`. Could we unify?
> > > 
> > > 
> > > Sorry for the confusion, option I have added is called `-eravm-jump-table-density` and what I said is that I took naming from the common llvm option that is called `-jump-table-density`. Of course I can change it to `-eravm-jump-table-density-threshold`, but I just wanted to know the reason behind it.
> > 
> > 
> > So should we keep `-jump-table-density` or do we need this `-eravm` prefix? If the latter, I prefer a more complete key `-eravm-jump-table-density-threshold`. If the former, let's just reuse the one already available.
> 
> We introduced new custom option to reduce local changes, so yes former is preferable. I will rename it to `-eravm-jump-table-density-threshold`.

Thanks!
I've made [an FE branch](https://github.com/matter-labs/era-compiler-solidity/pull/53), but we need to test it manually.

**Comment by vladimirradosavljevic** [comment]
@hedgar2017 I have changed the option name to `-eravm-jump-table-density-threshold`.

**Comment by vladimirradosavljevic** [comment]
> > > > > > > Could you rename the CLI arg to `-eravm-jump-table-density-threshold`?
> > > > > > 
> > > > > > 
> > > > > > Common LLVM option is called `-jump-table-density`, so I took the naming from there and just added `era` prefix. Is there a particular reason why we need `-eravm-jump-table-density-threshold`?
> > > > > 
> > > > > 
> > > > > In Slack you mentioned `-era-jump-table-density`, neither nothing nor `-era`. Could we unify?
> > > > 
> > > > 
> > > > Sorry for the confusion, option I have added is called `-eravm-jump-table-density` and what I said is that I took naming from the common llvm option that is called `-jump-table-density`. Of course I can change it to `-eravm-jump-table-density-threshold`, but I just wanted to know the reason behind it.
> > > 
> > > 
> > > So should we keep `-jump-table-density` or do we need this `-eravm` prefix? If the latter, I prefer a more complete key `-eravm-jump-table-density-threshold`. If the former, let's just reuse the one already available.
> > 
> > 
> > We introduced new custom option to reduce local changes, so yes former is preferable. I will rename it to `-eravm-jump-table-density-threshold`.
> 
> Thanks! I've made [an FE branch](https://github.com/matter-labs/era-compiler-solidity/pull/53), but we need to test it manually.

If we pass threshold to 10 and get the numbers for EvmInterpreter like [here](https://github.com/matter-labs/compiler-tester/pull/362), I would say it works as expected.

**Comment by hedgar2017** [comment]
@vladimirradosavljevic nice! Added [here](https://github.com/matter-labs/compiler-tester/pull/362).

**Review by hedgar2017 — APPROVED** [review]

**Pull request merged**
