### PR TITLE
[EraVM][MC] Add missing variants of NOP instruction

### PR DESCRIPTION
**Pull request by atrosinenko**
Make NOP support the remaining combinations of operands.

Reorganize the tests: add `nop.(s|txt)` test files similar to those for arithmetic instructions, put the test cases for `nop`, `incsp` and `decsp` aliases to `sp-changes.(s|txt)` files.

### CODE REVIEW

**Comment by atrosinenko** [comment]
This implements the idea proposed in #483: make the backend able to represent any `nop` as if it is an arithmetic instruction and understand the specific forms as `nop`, `incsp` and `decsp`.

After the renaming takes place, the lines
```
def : InstAlias<"nop${cc}\t${dst0}", (NOPrrs R0, R0, stackout:$dst0, pred:$cc)>;
def : InstAlias<"nop${cc}\t${src0}", (NOPsrr R0, stackin:$src0, R0, pred:$cc)>;
def : InstAlias<"nop${cc}",          (NOPrrr R0, R0, R0, pred:$cc)>;
```
will be replaced by
```
def : InstAlias<"incsp${cc}\t${reg}",        (NOPrrs R0, R0, R0, GR256:$reg, 0, pred:$cc)>;
def : InstAlias<"incsp${cc}\t${imm}",        (NOPrrs R0, R0, R0, R0, i16imm:$imm, pred:$cc)>;
def : InstAlias<"incsp${cc}\t${reg}+${imm}", (NOPrrs R0, R0, R0, GR256:$reg, i16imm:$imm, pred:$cc)>;

def : InstAlias<"decsp${cc}\t${reg}",        (NOPsrr R0, R0, GR256:$reg, 0, R0, pred:$cc)>;
def : InstAlias<"decsp${cc}\t${imm}",        (NOPsrr R0, R0, R0, i16imm:$imm, R0, pred:$cc)>;
def : InstAlias<"decsp${cc}\t${reg}+${imm}", (NOPsrr R0, R0, GR256:$reg, i16imm:$imm, R0, pred:$cc)>;

def : InstAlias<"nop${cc}",                  (NOPrrr R0, R0, R0, pred:$cc)>;
```

Note that these are not "mnemonic aliases" and not even aliases for the specific 11-bit opcode: for example
```
nop r0, r0, stack+=[r1 + 42]
```
is `incsp r1 + 42`, but
```
nop r0, r1, stack+=[r1 + 42]
```
is not.

@hedgar2017 Is such usage of aliases acceptable?

**Comment by asl** [comment]
Looks reasonable to me. @sayon Will you please check the desired syntax in the tests?

**Review by sayon — APPROVED** [review]

**Review by hedgar2017 — CHANGES_REQUESTED** [review]
@sayon do we have a single source of truth for modifiers, where we can revamp them just like main mnemonics?

**Comment by atrosinenko** [comment]
> do we have a single source of truth for modifiers

@hedgar2017 Do you mean aliases (like `incsp r1, 42 -> nop r0, r0, stack+=[r1+42]`)? Or is it the question about `to_label` modifier from #567?

**Comment by sayon** [comment]
I am making a summary of concrete syntax ATM will include everything there @hedgar2017

**Comment by atrosinenko** [comment]
@hedgar2017 Which changes are planned to this PR?

**Review by hedgar2017 — APPROVED** [review]
@atrosinenko LGTM. Our changes only touch the other PR apparently.

**Review by hedgar2017 — APPROVED** [review]

**Pull request merged**
