### PR TITLE
TEST: Enable Attributor pass by default

### PR DESCRIPTION
**Pull request by vladimirradosavljevic**

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                 -inf ║
║ Best                               40.183 ║
║ Worst                             -148.718 ║
║ Total                              -1.966 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                               48.980 ║
║ Worst                             -2379.412 ║
║ Total                              -0.874 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                               99.235 ║
║ Worst                             -1327.704 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -3.636 ║
║ Best                                6.438 ║
║ Worst                             -23.529 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -3.820 ║
║ Best                                3.279 ║
║ Worst                             -16.038 ║
║ Total                              -1.562 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -2.663 ║
║ Best                                1.351 ║
║ Worst                             -46.120 ║
║ Total                              -0.130 ║
╚═══════════════════════════════════════════╝

```

**Comment by hedgar2017** [comment]
> Benchmark results:
> ```
> ╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
> ║ Mean                                 -inf ║
> ║ Best                               40.183 ║
> ║ Worst                             -148.718 ║
> ║ Total                              -1.966 ║
> ╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
> ║ Mean                                 -inf ║
> ║ Best                               48.980 ║
> ║ Worst                             -2379.412 ║
> ║ Total                              -0.874 ║
> ╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
> ║ Mean                                 -inf ║
> ║ Best                               99.235 ║
> ║ Worst                             -1327.704 ║
> ║ Total                               0.000 ║
> ╚═══════════════════════════════════════════╝
> 
> ╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
> ║ Mean                               -3.636 ║
> ║ Best                                6.438 ║
> ║ Worst                             -23.529 ║
> ║ Total                               0.034 ║
> ╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
> ║ Mean                               -3.820 ║
> ║ Best                                3.279 ║
> ║ Worst                             -16.038 ║
> ║ Total                              -1.562 ║
> ╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
> ║ Mean                               -2.663 ║
> ║ Best                                1.351 ║
> ║ Worst                             -46.120 ║
> ║ Total                              -0.130 ║
> ╚═══════════════════════════════════════════╝
> 
> ```
> 

Wow! What's going on?

**Comment by vladimirradosavljevic** [comment]
> > Benchmark results:
> > ```
> > ╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
> > ║ Mean                                 -inf ║
> > ║ Best                               40.183 ║
> > ║ Worst                             -148.718 ║
> > ║ Total                              -1.966 ║
> > ╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
> > ║ Mean                                 -inf ║
> > ║ Best                               48.980 ║
> > ║ Worst                             -2379.412 ║
> > ║ Total                              -0.874 ║
> > ╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
> > ║ Mean                                 -inf ║
> > ║ Best                               99.235 ║
> > ║ Worst                             -1327.704 ║
> > ║ Total                               0.000 ║
> > ╚═══════════════════════════════════════════╝
> > 
> > ╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
> > ║ Mean                               -3.636 ║
> > ║ Best                                6.438 ║
> > ║ Worst                             -23.529 ║
> > ║ Total                               0.034 ║
> > ╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
> > ║ Mean                               -3.820 ║
> > ║ Best                                3.279 ║
> > ║ Worst                             -16.038 ║
> > ║ Total                              -1.562 ║
> > ╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
> > ║ Mean                               -2.663 ║
> > ║ Best                                1.351 ║
> > ║ Worst                             -46.120 ║
> > ║ Total                              -0.130 ║
> > ╚═══════════════════════════════════════════╝
> > ```
> 
> Wow! What's going on?

I didn't expect the numbers to be this bad.
Maybe we can try enabling it again when we rebase to a newer version of the LLVM. I will create the ticket for it, and close this PR. What do you think?

**Comment by hedgar2017** [comment]
> > > Benchmark results:
> 
> > > ```
> 
> > > ╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
> 
> > > ║ Mean                                 -inf ║
> 
> > > ║ Best                               40.183 ║
> 
> > > ║ Worst                             -148.718 ║
> 
> > > ║ Total                              -1.966 ║
> 
> > > ╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
> 
> > > ║ Mean                                 -inf ║
> 
> > > ║ Best                               48.980 ║
> 
> > > ║ Worst                             -2379.412 ║
> 
> > > ║ Total                              -0.874 ║
> 
> > > ╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
> 
> > > ║ Mean                                 -inf ║
> 
> > > ║ Best                               99.235 ║
> 
> > > ║ Worst                             -1327.704 ║
> 
> > > ║ Total                               0.000 ║
> 
> > > ╚═══════════════════════════════════════════╝
> 
> > > 
> 
> > > ╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
> 
> > > ║ Mean                               -3.636 ║
> 
> > > ║ Best                                6.438 ║
> 
> > > ║ Worst                             -23.529 ║
> 
> > > ║ Total                               0.034 ║
> 
> > > ╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
> 
> > > ║ Mean                               -3.820 ║
> 
> > > ║ Best                                3.279 ║
> 
> > > ║ Worst                             -16.038 ║
> 
> > > ║ Total                              -1.562 ║
> 
> > > ╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
> 
> > > ║ Mean                               -2.663 ║
> 
> > > ║ Best                                1.351 ║
> 
> > > ║ Worst                             -46.120 ║
> 
> > > ║ Total                              -0.130 ║
> 
> > > ╚═══════════════════════════════════════════╝
> 
> > > ```
> 
> > 
> 
> > Wow! What's going on?
> 
> 
> 
> I didn't expect the numbers to be this bad.
> 
> Maybe we can try enabling it again when we rebase to a newer version of the LLVM. I will create the ticket for it, and close this PR. What do you think?

Up to you.
Do we know why the numbers are bad?

**Comment by vladimirradosavljevic** [comment]
> > > > Benchmark results:
> > 
> > 
> > > >
> > 
> > 
> > > > ╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
> > 
> > 
> > > > ║ Mean                                 -inf ║
> > 
> > 
> > > > ║ Best                               40.183 ║
> > 
> > 
> > > > ║ Worst                             -148.718 ║
> > 
> > 
> > > > ║ Total                              -1.966 ║
> > 
> > 
> > > > ╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
> > 
> > 
> > > > ║ Mean                                 -inf ║
> > 
> > 
> > > > ║ Best                               48.980 ║
> > 
> > 
> > > > ║ Worst                             -2379.412 ║
> > 
> > 
> > > > ║ Total                              -0.874 ║
> > 
> > 
> > > > ╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
> > 
> > 
> > > > ║ Mean                                 -inf ║
> > 
> > 
> > > > ║ Best                               99.235 ║
> > 
> > 
> > > > ║ Worst                             -1327.704 ║
> > 
> > 
> > > > ║ Total                               0.000 ║
> > 
> > 
> > > > ╚═══════════════════════════════════════════╝
> > 
> > 
> > > >
> > 
> > 
> > > > ╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
> > 
> > 
> > > > ║ Mean                               -3.636 ║
> > 
> > 
> > > > ║ Best                                6.438 ║
> > 
> > 
> > > > ║ Worst                             -23.529 ║
> > 
> > 
> > > > ║ Total                               0.034 ║
> > 
> > 
> > > > ╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
> > 
> > 
> > > > ║ Mean                               -3.820 ║
> > 
> > 
> > > > ║ Best                                3.279 ║
> > 
> > 
> > > > ║ Worst                             -16.038 ║
> > 
> > 
> > > > ║ Total                              -1.562 ║
> > 
> > 
> > > > ╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
> > 
> > 
> > > > ║ Mean                               -2.663 ║
> > 
> > 
> > > > ║ Best                                1.351 ║
> > 
> > 
> > > > ║ Worst                             -46.120 ║
> > 
> > 
> > > > ║ Total                              -0.130 ║
> > 
> > 
> > > > ╚═══════════════════════════════════════════╝
> > 
> > 
> > > >
> > 
> > 
> > > 
> > 
> > 
> > > Wow! What's going on?
> > 
> > 
> > I didn't expect the numbers to be this bad.
> > Maybe we can try enabling it again when we rebase to a newer version of the LLVM. I will create the ticket for it, and close this PR. What do you think?
> 
> Up to you. Do we know why the numbers are bad?

Didn't have a chance to investigate it and with these numbers, I don't think it is worth investigating it for now.

**Comment by akiramenai** [comment]
@vladimirradosavljevic 
> Maybe we can try enabling it again when we rebase to a newer version of the LLVM. I will create the ticket for it, and close this PR. What do you think?

Sounds reasonable. Also agree that it doesn't worth to investigate at least now. Attributor is not widely used I think, so what works in theory might not work in practice, and it might be the case here.

**Pull request closed without merging**
