### PR TITLE
Updates workflows to make them public.

### PR DESCRIPTION
**Pull request by yorik**
fix: BFT-355

### CODE REVIEW

**Comment by akiramenai** [comment]
@yorik is it still needed? If so, can we update the PR, review and merge?

**Comment by antonbaliasnikov** [comment]
Hi @yorik , if we change the `compiler-llvm` to `era-compiler-llvm`, this will break the testing, because the other repository will be tested, instead of this one. We cannot do that. We can change only `compiler-tester` repo here.

**Comment by yorik** [comment]
This will be needed to make the repo public, due to circle dependency with `compiler-tester` repo it has to be done in one go.

I think the plan was to sync `compiler-tester` into `era-compiler-tester`, and rename this repo into `era-compiler-llvm`, and at this moment merge this PR.

Do you know when and how this is going to public?

**Comment by akiramenai** [comment]
@yorik, @hedgar2017 said after we update LLVM to 17. Maybe it will happen next week as integration is what is left.

**Comment by hedgar2017** [comment]
> @yorik, @hedgar2017 said after we update LLVM to 17. Maybe it will happen next week as integration is what is left.

Just noticed that this repo's workflows are not refactored yet.
@antonbaliasnikov could you take a look?

**Pull request closed without merging**
