### PR TITLE
[SyncVM] Fix exponent constant folding implementation for 0^0 case.

### PR DESCRIPTION
**Pull request by PavelKopyl**
Fix exponent constant folding implementation for 0^0 case.
Adding more LIT tests for the exponent.

### CODE REVIEW

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Review by hedgar2017 — APPROVED** [review]
Nice!
The tests ended up being useful.

**Review by akiramenai — APPROVED** [review]

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.025 ║
║ Best                                2.410 ║
║ Worst                              -8.526 ║
║ Total                              -0.094 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.029 ║
║ Best                                5.769 ║
║ Worst                              -7.584 ║
║ Total                              -0.015 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.003 ║
║ Best                                2.817 ║
║ Worst                              -4.494 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.247 ║
║ Best                                0.000 ║
║ Worst                              -8.526 ║
║ Total                              -0.474 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.104 ║
║ Best                                0.000 ║
║ Worst                              -0.797 ║
║ Total                              -0.144 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.005 ║
║ Best                                0.000 ║
║ Worst                              -0.264 ║
║ Total                              -0.005 ║
╚═══════════════════════════════════════════╝

```

**Comment by hedgar2017** [comment]
@PavelKopyl the CI passed: https://github.com/matter-labs/compiler-tester/pull/303.
Please **squash** and merge.

**Comment by PavelKopyl** [comment]
> @PavelKopyl the CI passed: [matter-labs/compiler-tester#303](https://github.com/matter-labs/compiler-tester/pull/303).
> Please **squash** and merge.

That's good. The only thing is that yesterday I also pushed one more change to this branch, namely "Add a range check for the first param of '__signextend'" (this is what we have discussed yesterday). I guess I should remove that patch and restart CI. Is it OK?

**Comment by hedgar2017** [comment]
> > @PavelKopyl the CI passed: [matter-labs/compiler-tester#303](https://github.com/matter-labs/compiler-tester/pull/303).
> 
> > Please **squash** and merge.
> 
> 
> 
> That's good. The only thing is that yesterday I also pushed one more change to this branch, namely "Add a range check for the first param of '__signextend'" (this is what we have discussed yesterday). I guess I should remove that patch and restart CI. Is it OK?

Yeah, please do.

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.025 ║
║ Best                                0.323 ║
║ Worst                              -8.526 ║
║ Total                              -0.094 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.029 ║
║ Best                                0.938 ║
║ Worst                              -7.584 ║
║ Total                              -0.015 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.003 ║
║ Best                                0.050 ║
║ Worst                              -4.494 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.247 ║
║ Best                                0.000 ║
║ Worst                              -8.526 ║
║ Total                              -0.474 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.104 ║
║ Best                                0.000 ║
║ Worst                              -0.797 ║
║ Total                              -0.144 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.005 ║
║ Best                                0.000 ║
║ Worst                              -0.264 ║
║ Total                              -0.005 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.025 ║
║ Best                                0.323 ║
║ Worst                              -8.526 ║
║ Total                              -0.094 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.029 ║
║ Best                                0.938 ║
║ Worst                              -7.584 ║
║ Total                              -0.015 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.003 ║
║ Best                                0.050 ║
║ Worst                              -4.494 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.247 ║
║ Best                                0.000 ║
║ Worst                              -8.526 ║
║ Total                              -0.474 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.104 ║
║ Best                                0.000 ║
║ Worst                              -0.797 ║
║ Total                              -0.144 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.005 ║
║ Best                                0.000 ║
║ Worst                              -0.264 ║
║ Total                              -0.005 ║
╚═══════════════════════════════════════════╝

```

**Review by hedgar2017 — CHANGES_REQUESTED** [review]
But the performance regression shouldn't have happened 😞
Could you investigate?

**Comment by PavelKopyl** [comment]
> But the performance regression shouldn't have happened 😞
> Could you investigate?

I fully agree. We should have not changes in the testing results at all, just because there is not corresponding functionality in the FE.
Could you please, point out to a guide (if any) how to start debugging such an issues? First, I'd like to find a test that slows down -7.584%.

**Comment by hedgar2017** [comment]
> > But the performance regression shouldn't have happened 😞
> > Could you investigate?
> 
> I fully agree. We should have not changes in the testing results at all, just because there is not corresponding functionality in the FE. Could you please, point out to a guide (if any) how to start debugging such an issues? First, I'd like to find a test that slows down -7.584%.

You just need to build the tester locally with two branches and compare the output for corresponding tests.

**Comment by PavelKopyl** [comment]
> > > But the performance regression shouldn't have happened 😞
> > > Could you investigate?
> > 
> > 
> > I fully agree. We should have not changes in the testing results at all, just because there is not corresponding functionality in the FE. Could you please, point out to a guide (if any) how to start debugging such an issues? First, I'd like to find a test that slows down -7.584%.
> 
> You just need to build the tester locally with two branches and compare the output for corresponding tests.

Thanks. But how can I find tests that causes maximum divergence from the mean value? I tried to grep the CI log, but I couldn't find them.

**Comment by hedgar2017** [comment]
> > > > But the performance regression shouldn't have happened 😞
> > > > Could you investigate?
> > > 
> > > 
> > > I fully agree. We should have not changes in the testing results at all, just because there is not corresponding functionality in the FE. Could you please, point out to a guide (if any) how to start debugging such an issues? First, I'd like to find a test that slows down -7.584%.
> > 
> > 
> > You just need to build the tester locally with two branches and compare the output for corresponding tests.
> 
> Thanks. But how can I find tests that causes maximum divergence from the mean value? I tried to grep the CI log, but I couldn't find them.

Tests are in [the log](https://github.com/matter-labs/compiler-llvm/actions/runs/5900345307/job/16005279352?pr=278) under 'Comparing'.

**Comment by PavelKopyl** [comment]
> > > > > But the performance regression shouldn't have happened 😞
> > > > > Could you investigate?
> > > > 
> > > > 
> > > > I fully agree. We should have not changes in the testing results at all, just because there is not corresponding functionality in the FE. Could you please, point out to a guide (if any) how to start debugging such an issues? First, I'd like to find a test that slows down -7.584%.
> > > 
> > > 
> > > You just need to build the tester locally with two branches and compare the output for corresponding tests.
> > 
> > 
> > Thanks. But how can I find tests that causes maximum divergence from the mean value? I tried to grep the CI log, but I couldn't find them.
> 
> Tests are in [the log](https://github.com/matter-labs/compiler-llvm/actions/runs/5900345307/job/16005279352?pr=278) under 'Comparing'.

Great, thank you!

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.025 ║
║ Best                                0.323 ║
║ Worst                              -8.526 ║
║ Total                              -0.093 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.029 ║
║ Best                                0.938 ║
║ Worst                              -7.584 ║
║ Total                              -0.015 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.003 ║
║ Best                                0.050 ║
║ Worst                              -4.494 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.247 ║
║ Best                                0.000 ║
║ Worst                              -8.526 ║
║ Total                              -0.474 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.104 ║
║ Best                                0.000 ║
║ Worst                              -0.797 ║
║ Total                              -0.144 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.005 ║
║ Best                                0.000 ║
║ Worst                              -0.264 ║
║ Total                              -0.005 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Comment by zksync-admin-bot2** [comment]
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

**Review by hedgar2017 — APPROVED** [review]

**Pull request merged**
